### ISSUE TITLE
Implement retry for single file when IO error occurs

### ISSUE THREAD

**Issue by sergtk** [sergtk/smart_hasher#15]
Sometimes following error occurs:

```
Traceback (most recent call last): 
  File "...\smart_hasher.py", line 268, in <module>
    e = handle_input_files()
  File "...\smart_hasher.py", line 260, in handle_input_files
    h = handle_input_file(input_file_name)
  File "...\smart_hasher.py", line 162, in handle_input_file
    hash = calc_hash(input_file_name)
  File "...\smart_hasher.py", line 75, in calc_hash
    data = f.read(file_chunk_size)
OSError: [Errno 22] Invalid argument
```

It may occurs when when specific file is not available for short time, e.g. short shortage in cloud service.

It is good to retry calculating hash for this file. This is especially important when hash should be calculated for many files, and error in one file interrupt whole workflow.

So by default retry count should be 3, after this file is skipped.
Following command line key should be implemented:
`--retry-count-for-file-read-error` - default is 3. Retry count on file reading error. If file can't be read after retry count, then it is skipped.

Pause should be applied here.

Check if there is some python library similar to C# one https://www.nuget.org/packages/polly

**Comment by sergtk** [comment]
Consider calculation of file average download speed
