### ISSUE TITLE
Exception thrown with ValueError: math domain error in function util.convert_size_to_display()

### ISSUE THREAD

**Issue by sergtk** [sergtk/smart_hasher#34]
Exception thrown on calculation hash for one of the multiple files with size 4095 Mb:

````
Traceback (most recent call last):maining time: 0:16:12. File average speed: 4.11 MiB/sec. Recent speed: 1.63 MiB/sec.
  File "<path>\smart_hasher\smart_hasher.py", line 242, in <module>
    exit_code = handle_input_files(hash_storage)
  File "<path>\smart_hasher\smart_hasher.py", line 177, in handle_input_files
    h = handle_input_file(hash_storage, input_file_name)
  File "<path>\smart_hasher\smart_hasher.py", line 64, in handle_input_file
    calc_res = calc.run()
  File "<path>\smart_hasher\hash_calc.py", line 133, in run
    res = self._run_single()
  File "<path>\smart_hasher\hash_calc.py", line 102, in _run_single
    speed_readable = util.convert_size_to_display(speed);
  File "<path>\smart_hasher\util.py", line 22, in convert_size_to_display
    i = int(math.floor(math.log(size_bytes, 1024)))
ValueError: math domain error
````

**Comment by sergtk** [comment]
It looks like the function `util.convert_size_to_display` failed during the switch from daylight time. This resulted in negative speed calculation. So after the fix the `util.convert_size_to_display` handles negative values correctly.

In fact it is good to implement speed measurements so that daylight does not influence on speed calculation, e.g. does not use current time (h, m, s). But since this is not critical for this application use cases and may occur very rarely the simple fix above is ok.

E.g. [time.time()](https://docs.python.org/3/library/time.html#time.time) can be used instead of `datetime.now()` in the class `FileHashCalc`
